compile-time type-constrained collection
fair-acc/opencmw-cpp pull request #127
Opened 2022-02-18 09:25 UTC by RalphSteinhagen

It is intended to be used with concept constraints to exchange collections of heterogeneous types <br>
as parameters between user-code and methods, e.g. (N.B. 'DataSet' being a concept type-constraint):

```cpp
template <DataSet... Ts>
void func(const opencmw::collection<Ts..> &dataSets) { ... }
```

<b>usage examples:</b>
```cpp
using opencmw::collection;
collection<size_t, float, char> c {1LU, 1.0f, 'a'};
c.push_back('c');

c.visit([](size_t &arg) noexcept { /*...*/ }, // need one type-specific visitor for each type:
    [](float &arg) noexcept { /*...*/ },
    [](char &arg) noexcept { /*...*/ },
    []<typename T>(T &arg) noexcept { /*...*/ }); // and/or: generic type fall-back visitor lambda.
```

<b>alternate list-style construction:</b>
```cpp
auto       c1 = collection{1LU, 1.0f, 'c'};
collection c2 = {1LU, 1.0f, 'c'};
```

authors: Matthias Kretz @mattkretz and Ralph J. Steinhagen @RalphSteinhagen

2022-02-18 11:10 UTC, mattkretz requested changes
see inline comments

2022-02-18 11:10 UTC, mattkretz commented on src/core/include/collection.hpp
> +                _items);
Much simpler:
```c++
(..., std::ranges::for_each(std::get<std::vector<Ts>>(_items), visitor));
```

2022-02-18 11:10 UTC, mattkretz commented on src/core/include/collection.hpp
> +        std::get<std::vector<std::remove_cvref_t<T>>>(_items).remove(std::forward<T>(e));
`std::vector` has no member named `remove` , no? Did you add a test for `collection::remove`?

2022-02-18 11:10 UTC, mattkretz commented on src/core/include/collection.hpp
> +    friend constexpr bool operator==(const collection<Ts1...> &lhs, const collection<Ts2...> &rhs) noexcept;
This is still a new language feature for me, but can't you simply default both operators? If not, I'd implement them right here, rather than pulling the name out of the `collection` namespace.

2022-02-18 11:37 UTC, RalphSteinhagen commented on src/core/include/collection.hpp
> +    requires std::disjunction_v<std::is_same<std::decay_t<T>, Ts>...>
well spotted. Force of habit of using `std::decay`. It's changed now.

2022-02-18 11:38 UTC, RalphSteinhagen commented on src/core/include/collection.hpp
> +        std::get<std::vector<std::remove_cvref_t<T>>>(_items).push_back(std::forward<T>(e));
removed

2022-02-18 11:45 UTC, RalphSteinhagen commented on src/core/include/collection.hpp
> +    [[nodiscard]] constexpr std::size_t size() const noexcept { std::size_t size = 0; std::apply([&size]<typename... T>(T & ...v) { (..., (size += v.size())); }, _items); return size; }
doesn't seem quite right (according to the unit-tests):
```cpp
collection testCollection7 = { 1LU, 1.0f, 'c', 'b' };
REQUIRE(testCollection7.size() == 4);
```
yields:
```
opencmw-cpp/src/core/test/collection_tests.cpp:60: Failure:
  REQUIRE(testCollection7.size() == 4)
with expansion:
  6 == 4
```
my guess is that it's because of `Ts...` may contain duplicate types (here: 'char') that with the fold expression on `Ts` are counted twice.

2022-02-18 11:48 UTC, RalphSteinhagen commented on src/core/include/collection.hpp
> +        std::get<std::vector<std::remove_cvref_t<T>>>(_items).remove(std::forward<T>(e));
done

2022-02-18 11:50 UTC, RalphSteinhagen commented on src/core/include/collection.hpp
> +        std::get<std::vector<std::remove_cvref_t<T>>>(_items).remove(std::forward<T>(e));
`std::vector` has [erase](https://en.cppreference.com/w/cpp/container/vector/erase) albeit being called with an iterator range. I am open for suggestion regarding alternate names for `remove(e`.

2022-02-18 11:51 UTC, RalphSteinhagen commented on src/core/include/collection.hpp
> +        std::get<std::vector<std::remove_cvref_t<T>>>(_items).remove(std::forward<T>(e));
and yes, the unit-test for remove was missing... now added. Thanks!

2022-02-18 12:11 UTC, RalphSteinhagen commented on src/core/include/collection.hpp
> +    friend constexpr bool operator==(const collection<Ts1...> &lhs, const collection<Ts2...> &rhs) noexcept;
Unfortunately couldn't use the default generated spaceship operator `<=>` because the template depends on `Ts...` which may contain duplicate types and even if the `_items` are identical differ because of template type signature differences.

E.g. one would expect that collections `c1` and `c2` are equal, regardless of how they were constructured:
```cpp
collection c1{1, 1.0f, 'a'};
c1.push_back('b');
collection c2{1, 1.0f, 'a'. 'b'};
assert c1 == c2;
```
The above assert would fail w/o the specific `<=>` operator because c1 and c2 have signatures of `collection<int, float, char>` and `collection<int, float, char, char>` while the internal `_items` signatures are the same.

2022-02-18 12:14 UTC, RalphSteinhagen commented on src/core/include/collection.hpp
> +    constexpr collection(Ts... element) noexcept { (..., push_back(element)); }
What additional function would this have in addition to the existing constructor? Aren't they ambiguous then?

2022-02-18 14:10 UTC, mattkretz commented on src/core/include/collection.hpp
> +    constexpr collection(Ts... element) noexcept { (..., push_back(element)); }
```c++
using my_collection collection<int, float>;
my_collection c(1, 2, 3, 1.1f, 3);
// without my ctor only the following is allowed:
my_collection c(1, 1.1f);
```

2022-02-19 11:24 UTC, RalphSteinhagen commented on src/core/include/collection.hpp
> +    [[nodiscard]] constexpr std::size_t size() const noexcept { std::size_t size = 0; std::apply([&size]<typename... T>(T & ...v) { (..., (size += v.size())); }, _items); return size; }
done -- solved by CTAD example by Matthias Kretz: https://godbolt.org/z/oYjcYqT3T

2022-02-19 11:25 UTC, RalphSteinhagen commented on src/core/include/collection.hpp
> +    constexpr collection(Ts... element) noexcept { (..., push_back(element)); }
done -- solved by CTAD example by @mattkretz : https://godbolt.org/z/oYjcYqT3T

2022-02-19 11:25 UTC, RalphSteinhagen commented on src/core/include/collection.hpp
> +    [[nodiscard]] constexpr std::size_t capacity() const noexcept { std::size_t size = 0; std::apply([&size]<typename... T>(T & ...v) { (..., (size = std::max(size, v.capacity()))); }, _items); retur
done -- solved by CTAD example by @mattkretz : https://godbolt.org/z/oYjcYqT3T

2022-02-19 11:26 UTC, RalphSteinhagen commented on src/core/include/collection.hpp
> +        std::get<std::vector<std::remove_cvref_t<T>>>(_items).remove(std::forward<T>(e));
done -- needed `std::decay_t` though

2022-02-19 11:26 UTC, RalphSteinhagen commented on src/core/include/collection.hpp
> +                _items);
done -- solved by CTAD example by @mattkretz : https://godbolt.org/z/oYjcYqT3T

2022-02-19 11:26 UTC, RalphSteinhagen commented on src/core/include/collection.hpp
> +    friend constexpr bool operator==(const collection<Ts1...> &lhs, const collection<Ts2...> &rhs) noexcept;
done -- solved by CTAD example by @mattkretz : https://godbolt.org/z/oYjcYqT3T

2022-02-21 10:23 UTC, mattkretz approved these changes
LGTM. One thing you should probably add: The documentation should note that iteration (aka visitation) is sorted by types in the order the types appear in the template argument list. And that per type the order is determined by insertion order.

2022-02-21 19:46 UTC, merged