RxCpp and Disruptor integration
fair-acc/opencmw-cpp pull request #141
Opened 2022-03-03 18:44 UTC by ivan-cukic

2022-03-07 14:20 UTC, wirew0rm requested changes
Very nice work, the API feels really nice.

I left some comments on the cmake side. Since I have another PR which changes lots of things in the build system anyway, we should concentrate on the c++ side here, feel free to change things that are easy to fix and leave the rest for the cmake cleanup.

In the code I have some small things and a few questions about how things work.

<strike>On the API side I noticed that we hava a Source, for going from disruptor to Rx and wie have Aggregation which aggregates and translates back to the Disruptor. I was wondering if it would be more flexible to have Aggregation purely in Rx and then a separate Sink which republishes into the Disruptor. Or would this have a big impact on performance or API?</strike>
Misread the code, the aggregated events are not published into the Disruptor again, I was mislead by the way it is implemented in java here.

2022-03-09 06:51 UTC, ivan-cukic commented on src/disruptor/include/disruptor/Exception.hpp
> +        : message(std::move(msg)) {
Ok, though storing a reference to an exception is potentially unsafe WRT lifetime.

2022-03-09 06:51 UTC, ivan-cukic commented on CMakeLists.txt
> +set(CONAN_DISABLE_CHECK_COMPILER 1)
That was the idea, but it seems not to work. Will remove.

2022-03-09 06:55 UTC, ivan-cukic commented on src/disruptor/test/Rx_tests.cpp
> +    auto             deviceAStream  = disruptorSource.stream() | rxcpp::operators::filter(equalTo('a')) | rxcpp::operators::distinct_until_changed();
It is not, I've added a comment that it is there just to demonstrate the transformation chaining.

2022-03-09 06:57 UTC, ivan-cukic commented on src/disruptor/include/disruptor/Rx.hpp
> +                        if constexpr (TimeLimitedPolicy<Policy>) {
This is a passive timeout - that is, observed only if there are events from other streams.
I'll add the heartbeat option.

2022-03-09 07:02 UTC, ivan-cukic commented on src/disruptor/test/CMakeLists.txt
> +    target_include_directories (${name} SYSTEM PUBLIC ${rx_SOURCE_DIR}/Rx/v2/src)
Done. I'm not that fond of adding header-only things to target_link_libraries, but that /is/ the modern cmake way :)

2022-03-11 10:58 UTC, wirew0rm approved these changes
Great. Thanks for addressing the issues, looks really nice now!

2022-03-11 11:09 UTC, wirew0rm commented
restyled seems to be down, but I applied clang-format locally.

2022-03-11 11:45 UTC, merged