added non-multiplexed BasicSetting implementation
fair-acc/opencmw-cpp pull request #153
Opened 2022-04-04 12:14 UTC by RalphSteinhagen

BasicSetting is a class that synchronises access to a copyable type T object from multiple non-real-time and a single real-time threads. The one designated real-time thread will never wait to get access to the object.

The MutableOption determines whether the object is mutable by the non-real-time threads or real-time thread only. Changes to the setting is guarded by a scoped accessGuard (safe recommended use, similar to a ScopedLock), or low-level pair of
`acquire()` and `release()` (N.B. less safe, requires matching).

*Example usage*:

```cpp
using namespace opencmw;
using opencmw::MutableOption::RealTimeMutable;
BasicSetting&#60;int, NonRealTimeMutable&#62; setting; &#x2f;&#x2f; N.B. here 'int' is the setting type

{ // calling from non-real-time thread (N.B. mutable setting)
   auto guardedValue = setting.accessGuard&#60;AccessType::NonRealTime&#62;();
   REQUIRE(guardedValue == 0);
   guardedValue = 40;
   guardedValue += 2;
   REQUIRE(guardedValue == 42);
}

setting.replace<AccessType::NonRealTime>(43);

{ // calling from real-time thread (N.B. immutable setting)
   auto guardedValue = setting.accessGuard&#60;AccessType::RealTime&#62;();
   REQUIRE(guardedValue == 43);
   REQUIRE(std::is_const_v<std::remove_reference_t<decltype(guardedValue.get())>>);
   &#x2f;&#x2f; guardedValue = 43; &#x2f;&#x2f; should not compile
   REQUIRE(guardedValue == 43);
}
```

2022-04-07 19:36 UTC, mattkretz reviewed
I'm not finished reviewing. But no more time/energy for today...

2022-04-07 19:36 UTC, mattkretz commented on src/disruptor/include/BasicSetting.hpp
> +    [[nodiscard]] std::conditional_t<mutableBy == MutableOption::RealTimeMutable && threadType == AccessType::RealTime, T, const T> &acquire() noexcept {
`acquire`, `release`, `accessGuard`, and `replace` require a template argument when called. This works fine as long as the type of the `BasicSetting` is known. But if it's a dependent type, callers will have to use an additional `template` keyword, which I always avoid in user-facing API. E.g.
```c++
template <typename T>
void some_fun(BasicSetting<T, NonRealTimeMutable>& s) {
  auto g = s.template accessGuard<AccessType::NonRealTime>();
```

2022-04-08 09:26 UTC, RalphSteinhagen commented on src/disruptor/include/BasicSetting.hpp
> +    auto accessGuard() { return ScopedAccess<threadType>(this->_settingStore); }
:+1: in and corrected

2022-04-08 09:31 UTC, RalphSteinhagen commented on src/disruptor/include/BasicSetting.hpp
> + *
added

2022-04-08 11:47 UTC, RalphSteinhagen commented on src/disruptor/include/BasicSetting.hpp
> +    [[nodiscard]] std::conditional_t<mutableBy == MutableOption::RealTimeMutable && threadType == AccessType::RealTime, T, const T> &acquire() noexcept {
This is valid for the preferred protection/access through the `accessGuard`.
I added the non-templated `nonRealTimeAccessGuard()` and `realTimeAccessGuard()` specialisation. 

The `acquire`, `release`, and `replace` should normally not be called by "normal" users but only those that want/need to wrap/extend the functionality. Did not want to hide that option.

The rationale behind the NTTP was to optimise the access/guard performance at compile-time similar to the `const`-ness functionality, to avoid semi-function-signature duplication, and to enhance the symmetry between the `acquire`/`release` pattern for real-time and non-real-time thread access.

If I could, and it would be trivial, I would even try to remove the constexpr ifs and slim-down the detailed implementation.

2022-04-14 12:23 UTC, wirew0rm requested changes
Looks good with some small things that should/could be changed before merging.

2022-04-14 12:23 UTC, wirew0rm commented on src/disruptor/include/BasicSetting.hpp
> +    void     releaseIndex(unsigned idx) noexcept { control.store((idx & INDEX_BIT) | NEWDATA_BIT, std::memory_order_release); }
produces sign conversion compiler warning, can be fixed with explicit cast:
``` c++
void     releaseIndex(unsigned idx) noexcept { control.store(static_cast<int>((idx & INDEX_BIT) | NEWDATA_BIT), std::memory_order_release); }

```

2022-04-14 14:27 UTC, RalphSteinhagen commented on src/disruptor/include/BasicSetting.hpp
> + * The MutableOption determines whether the object is mutable by the non-real-time threads or real-time thread only.
done

2022-04-14 14:28 UTC, RalphSteinhagen commented on src/disruptor/include/BasicSetting.hpp
> +    void     releaseIndex(unsigned idx) noexcept { control.store((idx & INDEX_BIT) | NEWDATA_BIT, std::memory_order_release); }
:+1:

2022-04-14 14:31 UTC, RalphSteinhagen commented on src/disruptor/include/BasicSetting.hpp
> +    using SettingStoreType = std::conditional_t<mutableBy == MutableOption::RealTimeMutable, detail::RealtimeMutable<T>, detail::NonRealtimeMutable<T>>;
The `SettingsStoreType`s are sort of private implementation which may change. Found the Enum a bit more explicit and less abusable. Am open to change/open-up that interface if the need would arise in specific use-cases though.

2022-04-14 14:35 UTC, wirew0rm approved these changes
:+1:

2022-04-14 14:52 UTC, merged