split and extended BasicThreadPool implementation [5]
fair-acc/opencmw-cpp pull request #173
Opened 2022-05-24 15:00 UTC by RalphSteinhagen

* pool implements (NTTP-controllable) [IO,CPU]-bound pools
* support std::future callbacks (~classic std::asynch interface)
* improved thread affinity/scheduling handling
* tasks can be (optionally) named
* tasks can be (optionally) priority-queued
* tasks can be (optionally) bound to a specific CPU that is compatible with the set affinity mask

Some basic usage examples (see BasicThreadPool_example.cpp for details):
```cpp
using namespace std::chrono;
using opencmw::thread::getThreadName;

opencmw::BasicThreadPool<opencmw::CPU_BOUND> poolWork("CustomCpuPool", 1, 1); // pool for CPU-bound tasks with exactly 1 thread
opencmw::BasicThreadPool<opencmw::IO_BOUND>  poolIO("CustomIOPool", 1, 1000); // pool for IO-bound (potentially blocking) tasks with at least 1 and a max of 1000 threads
poolIO.keepAliveDuration() = seconds(10);                                     // keeps idling threads alive for 10 seconds
poolIO.waitUntilInitialised();                                                // wait until the pool is initialised (optional)
assert(poolIO.isInitialised());                                               // check if the pool is initialised

// enqueue and add task to list -- w/o return type
poolWork.execute([] { fmt::print("Hello World from thread '{}'!\n", getThreadName()); });
poolWork.execute([](const auto &...args) { fmt::print("Hello World from thread '{}'!\n", args...); }, getThreadName());

constexpr auto           func1  = [](const auto &...args) { return fmt::format("thread '{1}' scheduled task '{0}'!\n", getThreadName(), args...); };
std::future<std::string> result = poolIO.execute<"customTaskName">(func1, getThreadName());
// do something else ... get result, wait if necessary
std::cout << result.get() << std::endl;
poolIO.setAffinityMask({ true, true, true, false });
poolIO.execute<"task name", 20U, 2>([]() { fmt::print("Hello World from custom thread '{}'!\n", getThreadName()); }); // execute a task with a name, a priority and single-core affinity
try {
    poolIO.execute<"customName", 20U, 3>([]() { /* this potentially long-running task is trackable via it's 'customName' thread name */});
} catch (const std::invalid_argument &e) {
    fmt::print("caught exception: {}\n", e.what());
}
```

Example output:
```
thread 'BasicThreadPool' scheduled task 'customTaskName'!

Hello World from thread 'CustomCpuPool#1'!
Hello World from custom thread 'task name'!
Hello World from thread 'BasicThreadPool'!
caught exception: requested cpuID 3 incompatible with set affinity mask(4): [true, true, true, false]
```

2022-05-24 15:23 UTC, mattkretz commented on src/core/include/ThreadPool.hpp
> +            : fn(const_cast<Fn &&>(rhs.fn)) { throw 0; } // hack to initialize fn for non-DefaultConstructible types
Maybe only
```c++
wrapper(const wrapper &rhs);
```
without definition? I.e. make it fail when linking rather than at runtime.

2022-05-24 15:23 UTC, mattkretz commented on src/core/include/ThreadPool.hpp
> +        wrapper &operator=(wrapper &) { throw 0; }
same here, of course

2022-05-24 16:32 UTC, RalphSteinhagen commented on src/core/include/ThreadPool.hpp
> +            : fn(const_cast<Fn &&>(rhs.fn)) { throw 0; } // hack to initialize fn for non-DefaultConstructible types
@mattkretz unfortunately, the version with `wrapper(const wrapper &rhs);` does not compile. 

Part of the 'hackish' implementation is that this class derives from `std::function(...)` and needs to shadow the superordinate copy-asignment/constructor implementation.

2022-05-25 09:38 UTC, mattkretz commented on src/core/include/ThreadPool.hpp
> +            : fn(const_cast<Fn &&>(rhs.fn)) { throw 0; } // hack to initialize fn for non-DefaultConstructible types
Too bad. Maybe you want to consider a special-purpose `function` type like in https://godbolt.org/z/4GzGoh68z?

2022-05-25 11:53 UTC, mattkretz approved these changes
LGTM

2022-05-25 14:52 UTC, mattkretz requested changes
I'd be afraid of the `Task` comparison operators biting at some point. And it'll probably be mind-boggling why results are inconsistent.

2022-05-25 14:52 UTC, mattkretz commented on src/core/include/ThreadPool.hpp
> +    auto                operator<=>(const Task &other) const noexcept { return priority <=> other.priority; }
This is strange. You can have `a == b` be false while `is_eq(a <=> b)` is true. `auto` in this case will be `std::strong_ordering`. But what you actually seem to want is a partial ordering (like with NaNs in floating-point).

2022-05-25 17:22 UTC, RalphSteinhagen commented on src/core/include/ThreadPool.hpp
> +    auto                operator<=>(const Task &other) const noexcept { return priority <=> other.priority; }
@mattkretz removed `operator==` wasn't called even for tasks with matching priorities.

2022-05-25 20:29 UTC, mattkretz approved these changes

2022-05-30 06:25 UTC, merged