Client: keep query params
fair-acc/opencmw-cpp pull request #218
Opened 2022-09-08 18:13 UTC by wirew0rm

Work in progress, tests are still failing.

Make the client use the path and the query to make subscriptions as opposed to only the path. This is required to allow subscriptions with different parameters/filters to be notified.

Also cleans up some warnings and other small things.

2022-09-10 08:30 UTC, RalphSteinhagen requested changes
some minor changes to be discussed: 
* whether `URI::localPart()` should return also the fragment, ie. `<path>?<query_parm>#<fragment>` 
* naming: `URI::localPart()` to `URI::relativeRef()` as described in [rfc3986 - Section 4.2](https://www.rfc-editor.org/rfc/rfc3986#section-4.2)

Otherwise, LGTM! :+1:

2022-09-10 08:30 UTC, RalphSteinhagen commented on src/core/include/URI.hpp
> +    inline std::optional<std::string> localPart() const noexcept { return returnOpt(merge_adjacent_string_views({_path.data(), _path.size()+1}, _query)); } // path + query
N.B. this should work for well-formatted URIs.

I like the definition of this `localPart()` because there is a recurring need. I wonder whether we shouldn't also include the fragment `#...` part of the URI. The server may (/should) drop this for most cases.
However, since we use this also internally to our application the fragment can convey important app-specific information.

2022-09-10 08:48 UTC, RalphSteinhagen commented on src/client/include/Client.hpp
> +        opencmw::majordomo::zmq_invoke(zmq_setsockopt, con._socket, ZMQ_SUBSCRIBE, serviceName.data(), serviceName.size() - 1).assertSuccess(); // string_view size includes termination byte
This produces an error because the string_view not actually being NULL-terminated `\0`. 

Using a copy-to-string workaround like:
```cpp
        std::string serviceName2(serviceName);
        opencmw::majordomo::zmq_invoke(zmq_setsockopt, con._socket, ZMQ_SUBSCRIBE, serviceName2.data(), serviceName2.size()).assertSuccess(); // string_view size includes termination byte
```
seems to fix this but should look into a more elegant version.

2022-09-10 08:48 UTC, RalphSteinhagen commented on src/client/include/Client.hpp
> +        opencmw::majordomo::zmq_invoke(zmq_setsockopt, con._socket, ZMQ_UNSUBSCRIBE, serviceName.data(), serviceName.size() - 1).assertSuccess();
as above for the 'subscribe' version.

2022-09-12 09:28 UTC, wirew0rm commented on src/client/include/Client.hpp
> +        opencmw::majordomo::zmq_invoke(zmq_setsockopt, con._socket, ZMQ_SUBSCRIBE, serviceName.data(), serviceName.size() - 1).assertSuccess(); // string_view size includes termination byte
This was due to an error in my implementation of `localPart()` with empty query returning one character too much. Removed the -1 part.

2022-09-12 09:29 UTC, wirew0rm commented on src/core/include/URI.hpp
> +    inline std::optional<std::string> localPart() const noexcept { return returnOpt(merge_adjacent_string_views({_path.data(), _path.size()+1}, _query)); } // path + query
Renamed to `relativeRefNoFragment()` and introduced an additional `relativeRef()`.

2022-09-12 09:34 UTC, RalphSteinhagen approved these changes
As discussed and thanks for the changes! LGTM!

2022-09-16 14:02 UTC, merged