Fix subscriptions via REST when using params
fair-acc/opencmw-cpp pull request #331
Opened 2023-11-24 13:45 UTC by frankosterfeld

Do not lose params when subscribing to a topic via REST.

Bump cpp-httplib to newest version, as it fixes an encoding error
with query parameters encoded in query parameters (SubscriptionContext)
when used with redirects.

TODO: Something going wrong (with the httplib update?) when I try to use it in opendigitizer

2023-12-02 08:38 UTC, RalphSteinhagen requested changes
Thanks for the changes. I think we should meet and reiterate on the mapping between URI and MDP protocol. 

The URI's 'path' component should not be broken up on the '/' but map one-to-one to the MDP's 'service name' and the URI's 'query paramters' to the MDP's '[request, reply] topic'. 

I.e. a REST URI '[...]/DeviceName/Acquisition?filterA=...,filterB=...' maps to the MDP:
  * service name = '/DeviceName/Acquisition'
  * request topic = 'filterA=...,filterB=...'
  
Otherwise we mix two different routing concepts. For details see the [extended MDP](https://github.com/fair-acc/opencmw-cpp/blob/main/docs/Majordomo_protocol_comparison.pdf) and -- for reference only --the [original MDP](https://rfc.zeromq.org/spec/18/) definition (N.B. we added, stream-lined and made the in/out commands symmetric compared to the original MDP and more closely following the [URI](https://datatracker.ietf.org/doc/html/rfc3986) definition).

2023-12-04 10:05 UTC, frankosterfeld commented on concepts/majordomo/FilterSubscription_example.cpp
> -    AcquisitionWorker<"/DeviceName/Acquisition"> acquisitionWorker(broker);
Actually, there's another case where mdp/mds and http URIs have the form service/topic?params with non-empty topic, and that's GET/SET to obtain certain objects:

With the opendigitizer dashboards service, the client first requests "/dashboards" to get the list of available dashboards, and then "/dashboards/dashboard1", "/dashboards/dashboard2" ... to get the data for the individual dashboards. Should the "dashboard1", "dashboard2" part be moved to a query param? Like:

"/dashboards" -> returns list of dashboards
"/dashboards?dashboard=dashboard1&what=header" -> returns header of dashboard1

etc.

2023-12-04 15:03 UTC, RalphSteinhagen commented on concepts/majordomo/FilterSubscription_example.cpp
> -    AcquisitionWorker<"/DeviceName/Acquisition"> acquisitionWorker(broker);
> serviceName: "device1/Acquisition" (no leading slash)

N.B. we discussed/decided earlier that we enforce a leading '/' slash for all services. For the URI this is not strictly enforced by the RFC standard but in 98% of the cases it used as such. The remaining ambiguity would have been whether the `/` is the trailing one and belonging to the authority or leading slash of the 'path' component.

2023-12-04 15:04 UTC, frankosterfeld commented on concepts/majordomo/FilterSubscription_example.cpp
> -    AcquisitionWorker<"/DeviceName/Acquisition"> acquisitionWorker(broker);
The issue here is how to parse e.g. `http://localhost:8080/dashboards/dashboard1` (same for mds/mdp://) - the RestBackend can't know if service: `dashboards/dashboard` is meant (if service names can have "/" inside), or service `dashboards`, with topic `dashboard1`.

2023-12-15 10:21 UTC, RalphSteinhagen approved these changes

2023-12-15 11:32 UTC, ivan-cukic approved these changes

2023-12-15 12:17 UTC, merged