Frank/majordomo heartbeat et al
fair-acc/opencmw-cpp pull request #53
Opened 2021-11-11 13:24 UTC by frankosterfeld

2021-11-22 16:55 UTC, RalphSteinhagen requested changes
see comments above

2021-11-22 17:33 UTC, frankosterfeld commented on src/majordomo/include/majordomo/BasicMdpWorker.hpp
> +            case Command::Get:
Understood, I'd change that in the patch for the RequestHandler though and leave this here as is.

2021-11-30 09:37 UTC, frankosterfeld commented on src/majordomo/include/majordomo/BasicMdpWorker.hpp
> +            pollOk            = result.isValid();
Removing

2021-11-30 09:51 UTC, frankosterfeld commented on src/majordomo/include/majordomo/BasicMdpWorker.hpp
> +        } while (pollOk && !_shutdownRequested);
Where would the context be closed? I don't see API to check for it and we close the context only in ~Context(). With "jthread has been politely requested to stop"? Do you mean using the stop_token functionality instead of the shutdownRequested atomic?

2021-11-30 09:51 UTC, frankosterfeld commented on src/majordomo/include/majordomo/Broker.hpp
> +    static int toMilliseconds(auto duration) {
I moved these to a struct now, using std::chrono::milliseconds using an explicit cast inline where needed. I couldn't figure out how to spell out the types for the member variables using mp-units. We can review whether we want to use std::chrono here or switch to mp-units.

2021-11-30 09:52 UTC, frankosterfeld commented on src/majordomo/include/majordomo/ZmqPtr.hpp
> +            debugWithLocation(location) << "Ignored error result:" << std::strerror(_error);
Agreed, at least for anything more complex than these here.

2021-12-01 19:49 UTC, RalphSteinhagen approved these changes
As discussed. :+1:

2021-12-01 19:49 UTC, merged