Frank/pathbased pubsub
fair-acc/opencmw-cpp pull request #75
Opened 2021-12-06 18:05 UTC by frankosterfeld

Still missing: SUB support in client class, more advanced query-based topic matching

2021-12-13 10:15 UTC, RalphSteinhagen requested changes
Looks good, two mains things to be addressed:
 a) decoupling of `notify(MdpMessage)` interface similar to the REST-Broker decoupling
 b) SubscriptionMatcher checks only for paths, option
    b.1) min-impl: matching of exact <key[=<value] pairs of notify and subscription topic
    b.2) implement the `TimingCtx` together with the [Majordomo]Worker impl.

2021-12-13 10:15 UTC, RalphSteinhagen commented on src/majordomo/include/majordomo/SubscriptionMatcher.hpp
> +
`testPathOnly(...)` -> missing `testPathAndContext(...)` 

should be address now or latest once the [Majordomo]Worker with the necessary context `<C>` definitions is available
Two options:
  a) min-impl: matching of exact <key[=<value] pairs of notify and subscription topic (N.B. 'key' being case-insensitive, the 'values' not (necessarily), N.B 'values' being optional)
  b) implement 'TimingCtx'  and `Filter` interface/concept (tbd.)

2021-12-13 10:15 UTC, RalphSteinhagen commented on src/majordomo/test/subscriptionmatcher_tests.cpp
> +}
to note: cross-check w.r.t. Java-based [unit-test](https://github.com/fair-acc/opencmw-java/blob/d1a0cc795ff4d3b3369bb374f27190bd6c629895/core/src/test/java/io/opencmw/filter/SubscriptionMatcherTest.java) cases

2021-12-13 10:15 UTC, RalphSteinhagen commented on src/majordomo/include/majordomo/BasicMdpWorker.hpp
> +        static std::atomic<int> idCounter     = 0;
for example, [see](https://github.com/fair-acc/opencmw-cpp/blob/0be90a0143e03e7b06ea79fd6423173b21ab4f66/src/majordomo/include/majordomo/RestBackend.hpp#L47-L75):
```cpp
    struct Worker {
        Socket         socket;
        zmq_pollitem_t pollItem{};


        Worker(const Context &context, const std::string &address)
            : socket(context, ZMQ_DEALER) {
            pollItem.socket = socket.zmq_ptr;
            pollItem.events = ZMQ_POLLIN;


            zmq_invoke(zmq_connect, socket, address).assertSuccess();
        }
    };


    std::unordered_map<std::thread::id, Worker> _workers;
    std::mutex                                  _workersLock;


    // Function that returns this thread's worker instance
    Worker &workerForThisThread() {
        auto threadId = std::this_thread::get_id();
        {
            std::lock_guard lock{ _workersLock };
            if (!_workers.contains(threadId)) {
                _workers.emplace(std::piecewise_construct,
                        std::forward_as_tuple(threadId),
                        std::forward_as_tuple(_context, URI<>::factory(_address).toString()));
            }
            return _workers.at(threadId);
        }
    }
```

2021-12-13 11:22 UTC, frankosterfeld commented on src/majordomo/include/majordomo/BasicMdpWorker.hpp
> +    const Context                 _notifyContext;
Wouldn't that fail if context is used tcp:/, while notify always uses inproc?

2021-12-13 13:48 UTC, frankosterfeld commented on src/majordomo/include/majordomo/BasicMdpWorker.hpp
> +    const Context                 _notifyContext;
actually, the whole API doesn't allow for broker<->worker pubsub via tcp... but connecting the notify sockets fails when trying to reuse the broker context.

2021-12-13 13:49 UTC, frankosterfeld commented on src/majordomo/include/majordomo/BasicMdpWorker.hpp
> +    void notify(std::string topic, std::string body) {
Done, although most fields of the message are overwritten, only topic, body, error remain.

2021-12-13 13:49 UTC, frankosterfeld commented on src/majordomo/include/majordomo/BasicMdpWorker.hpp
> +    void notifyError(std::string topic, std::string error) {
Done

2021-12-13 13:51 UTC, frankosterfeld commented on src/majordomo/include/majordomo/BasicMdpWorker.hpp
> +        assert(_workerSocket);
these are checking internal invariants, not valid error condituions. if connectToBroker succeeds, the socket must be set.

2021-12-13 13:57 UTC, frankosterfeld commented on src/majordomo/include/majordomo/SubscriptionMatcher.hpp
> +
I'd do that separately, as the design of the Filters might depend also on the serialisation. (I have a TimingCtx class now, I could do a first simple version quickly)

2021-12-13 15:07 UTC, RalphSteinhagen commented on src/majordomo/include/majordomo/BasicMdpWorker.hpp
> +        assert(_workerSocket);
I agree that these are useful during development. Once these internal invariants are established (and never fail) they are basically dead-code and could and should be removed -> 'zero waste' principle

2021-12-13 15:15 UTC, RalphSteinhagen commented on src/majordomo/include/majordomo/SubscriptionMatcher.hpp
> +
There is already the refl-cpp solution for serialisation using the 
```cpp
ENABLE_REFLECTION_FOR(className, field1, field2, field3)
```
visitor pattern. If the `ENABLE_REFLECTION_FOR` is defined, then one can loop through all member fields and methods. using the
```cpp
refl::util::for_each(refl::reflect(value).members, [&](const auto member, [[maybe_unused]] const auto index) {
 // [..]
}
```
looping of the members. Have a look at the `opencmw::serialise(IoBuffer &buffer, const T &value, const uint8_t hierarchyDepth)` or [refl-cpp](https://github.com/veselink1/refl-cpp) directly for usage examples.

2021-12-13 15:16 UTC, RalphSteinhagen commented on src/majordomo/test/subscriptionmatcher_tests.cpp
> +}
The Java test-cases also includes the query parameters (or ignoring thereof if it's path-only checking)

2021-12-13 15:20 UTC, frankosterfeld commented on src/majordomo/test/subscriptionmatcher_tests.cpp
> +}
That's the"if 0"'d test below. Then there's another one using TimingCtx and mimetypes, which I didn't include here yet.

2021-12-13 18:17 UTC, frankosterfeld commented on src/majordomo/include/majordomo/BasicMdpWorker.hpp
> +        assert(_workerSocket);
I added another commit removing the internal checks

2021-12-14 17:06 UTC, RalphSteinhagen approved these changes

2021-12-14 17:10 UTC, merged